// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewQuestion struct {
	Title          string  `json:"title"`
	Response       string  `json:"response"`
	UserID         *string `json:"userId"`
	CreatedAt      *string `json:"createdAt"`
	LastModifiedAt *string `json:"lastModifiedAt"`
}

type Question struct {
	Title          string  `json:"title"`
	ID             string  `json:"id"`
	User           *User   `json:"user"`
	WithResponse   *bool   `json:"withResponse"`
	Response       string  `json:"response"`
	CreatedAt      *string `json:"createdAt"`
	LastModifiedAt *string `json:"lastModifiedAt"`
}

type User struct {
	ID    string  `json:"id"`
	Email *string `json:"email"`
	Name  string  `json:"name"`
}
